# .github/workflows/gitlab-stats.yml
name: Update GitLab Stats
on:
  schedule:
    - cron: "15 17 * * *" # UTC+7
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  gitlab-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: pip install requests types-requests mypy
      - run: mypy --strict generate_gitlab_stats.py
      - run: python generate_gitlab_stats.py
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gitlab-stats.svg
          git commit -m "Update GitLab stats" || echo "No changes"
          git pull --rebase origin main
          git push
